steps:
- name: gcr.io/cloud-builders/npm
  args: ['install']
  dir: 'container2'
  id: A
- name: gcr.io/cloud-builders/npm
  args: ['start']
  id: B
  dir: 'container2'
  waitFor: ['A']
- name: gcr.io/cloud-builders/npm
  args: ['install']
  dir: 'container1'
  waitFor: ['A']
  id: C
- name: gcr.io/cloud-builders/npm
  args: ['start']
  id: D
  dir: 'container1'
  waitFor: ['C']
- name: 'gcr.io/cloud-builders/docker'
  id: Docker network inspect cloudbuild
  args: ["network", "inspect", "cloudbuild"]
  waitFor: ['D']
- name: 'gcr.io/cloud-builders/docker'
  id: Docker ps before
  args: ["container", "ls", "--no-trunc"]
  waitFor: ['D']