version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_PASSWORD=postgres
  test-container:
    build: container1
networks:
  default:
    external:
      name: cloudbuild